name: fasttext_language_identification
channels:
    - conda-forge
    - defaults
dependencies:
    - python ==3.10.12
    - fasttext ==0.9.2
    - huggingface_hub ==0.24.6
    - numpy ==1.26.4
    - conda-pack