name: "siglip_text"
backend: "python"
max_batch_size: 32
default_model_filename: "siglip_text.py"

input [
    {
        name: "INPUT_IDS"
        data_type: TYPE_INT64
        dims: [64]
    }
]
output [
    {
        name: "EMBEDDING"
        data_type: TYPE_FP32
        dims: [1152]
    }
]

parameters: [
    {
        key: "EXECUTION_ENV_PATH",
        value: {string_value: "$$TRITON_MODEL_DIRECTORY/siglip_text.tar.gz"},
    }
]
instance_group [
    {
        kind: KIND_AUTO,
        count: 1
    }
]
version_policy: {latest: {num_versions: 1}}
dynamic_batching: {}
model_warmup: [
    {
        name: "batch_size_1"
        count: 5
        batch_size: 1
        inputs: {
            key: "INPUT_IDS"
            value: {
                data_type: TYPE_INT64
                dims: [64]
                zero_data: true
            }
        }
    },
    {
       name: "batch_size_2"
        count: 5
       batch_size: 2
       inputs: {
            key: "INPUT_IDS"
            value: {
                data_type: TYPE_INT64
                dims: [64]
                zero_data: true
            }
        }
    }
]